spring.application.name=spring-project
spring.profiles.active=prod
server.port=8081

app.lang=az,en,ru

app.active_status=true


mail.host=smtp.gmail.com
mail.port=587
mail.username=emrah@gmail.com
mail.password=123456
mail.from=java@developia.az

# Bütün t?tbiq üçün ümumi s?viyy?
logging.level.root=INFO
logging.console.enabled=true
logging.file.name=./logs/app.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
Root