spring.application.name=spring-project
spring.profiles.active=prod
server.port=8081

app.lang=az,en,ru

app.active_status=true


mail.host=smtp.gmail.com
mail.port=587
mail.username=emrah@gmail.com
mail.password=123456
mail.from=java@developia.az

