spring.datasource.url=jdbc:mysql://localhost:3306/webjava4
spring.datasource.username=root
spring.datasource.password=emrah1907
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.name="book prod"
spring.payment.api.url=http://localhost:8082